### PR TITLE
Add back Node 4 support

### LINKED ISSUE #8: restore node 4 compat
node 4 is still LTS and eslint still supports it; it'd be great to keep this runner working on node 4 without reintroducing babel-polyfill.

### PR DESCRIPTION
**Pull request by Turbo87**
This PR reverts parts of https://github.com/jest-community/jest-runner-eslint/pull/6 and resolves #8 

/cc @ljharb @rogeliog

### CODE REVIEW

**Comment by Turbo87** [comment]
@rogeliog FYI it seems that TravisCI is currently not enabled for this repo 🤔

**Comment by rogeliog** [comment]
@Turbo87 Great point! It broke after this repo moved to the jest-community org... I'll fix it cc: @orta

**Comment by rogeliog** [comment]
I just reconfigured Travis, it should work now... Do you mind repushing for Travis to pick it up?

**Comment by Turbo87** [comment]
@rogeliog on mobile right now, but you should be able to push to my branch too

**Comment by rogeliog** [comment]
Thanks a lot! 👏

**Pull request merged**
