### PR TITLE
fix: support Jest 29

### PR DESCRIPTION
**Pull request by SimenB**
https://jestjs.io/blog/2022/08/25/jest-29

### CODE REVIEW

**Comment by ljharb** [comment]
This is a semver-minor, not a patch.

**Comment by SimenB** [comment]
Yeah, released it as a minor 😅

https://github.com/jest-community/jest-runner-eslint/releases/tag/v1.1.0

**Comment by ljharb** [comment]
ah k, i just saw the "fix" :-)

**Comment by SimenB** [comment]
Yeah, that's what I figured 👍

**Pull request merged**
