### PR TITLE
chore: refresh lockfiles to get rid of security alert

### PR DESCRIPTION
**Pull request by SimenB**
It just complains about `set-value` which we get via `chokidar`, `sane` and `micromatch` - all development dependencies.

I just deleted the lockfiles and ran `yarn` again. Will merge if green

### CODE REVIEW

**Comment by ljharb** [comment]
seems simpler to get rid of the lockfiles for the examples.

**Comment by SimenB** [comment]
Yeah, let's

**Comment by SimenB** [comment]
`@babel/preset-env` depends on `levenary`, which is node 8+...

**Comment by SimenB** [comment]
I can force a lower version of `preset-env` to unblock. It's just a dev tool, so doesn't affect consumers

**Comment by ljharb** [comment]
That seems like a breaking change for preset-env; could you file an issue?

**Comment by SimenB** [comment]
Yeah, I added a comment to the PR which added it to babel

**Comment by SimenB** [comment]
Upstream fix: https://github.com/tanhauhau/levenary/pull/3

If merged and released we can upgrade again.

**Pull request merged**
